---
title: "CS 6476 Notes"
author: "Timothy Luna"
date: "8/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## [Python Helper Functions](notes/cs6476/cs6476helpers.py)

## Module 1

### [Lesson 1: Intro](notes/cs6476/Lesson_01.html)

## Module 2

### [Lesson 2: Images as Functions](notes/cs6476/Lesson_02.html)

### [Lesson 3: Filtering](notes/cs6476/Lesson_03.html)

### [Lesson 4: Linearity and Convolution](notes/cs6476/Lesson_04.html)

### [Lesson 5: Filters as Templates](notes/cs6476/Lesson_05.html)

### [Lesson 6: Edge Detection: Gradients](notes/cs6476/Lesson_06.html)

### [Lesson 7: Edge Detection: 2D Operators](notes/cs6476/Lesson_07.html)

### [Lesson 8: Hough Transform: Lines](notes/cs6476/Lesson_08.html)

### [Lesson 9: Hough Transform: Circles](notes/cs6476/Lesson_09.html)

### [Lesson 10: Generalized Hough Transform](notes/cs6476/Lesson_10.html)

## Module 3

### [Lesson 11: Fourier Transform](notes/cs6476/Lesson_10.html)

### [Lesson 12: Convolution in the Frequency Domain](notes/cs6476/Lesson_10.html)

### [Lesson 13: Aliasing](notes/cs6476/Lesson_10.html)

### [Lesson 14: Cameras and Images](notes/cs6476/Lesson_10.html)

### [Lesson 15: Perspective Imaging](notes/cs6476/Lesson_10.html)

### [Lesson 16: Stereo Geometry](notes/cs6476/Lesson_10.html)

### [Lesson 17: Epipolar Geometry](notes/cs6476/Lesson_10.html)

### [Lesson 18: Stereo Correspondence](notes/cs6476/Lesson_10.html)

### [Lesson 19: Extrinsic Camera Parameters](notes/cs6476/Lesson_10.html)

### [Lesson 20: Intrinsic Camera Parameters](notes/cs6476/Lesson_10.html)

### [Lesson 21: Calibrating Cameras](notes/cs6476/Lesson_10.html)

